### ISSUE TITLE
is it possible to add this ? very urgent would assist if necessary

### ISSUE THREAD

**Issue by therealelyayo** [GemGeorge/SniperPhish#1]
{{EMAIL}}

hello i would like to know if it would be possible to add this vaue = {{DOMAIN}} to app and the varible would be gotten from each email user.

lets say the reciver of mail is testi@gmail.com and testi@yahoo.com, would it be possible to get gmail.com and yahoo.com in html template by using {{DOMAIN}}.

awesome work i await your response

**Comment by GemGeorge** [comment]
Hi,

Thanks for your suggestion, this option will be included in the next update. In the meantime, you can use the generic field {{NOTES}} for this purpose. You are required to filter out the domain corresponding to each email and add it in the "Notes" field when creating User Group

**Comment by therealelyayo** [comment]
it has to happen on the fly as part of the html the notes can be used for something else but this is realy important
lets say the reciver of mail is testi@gmail.com and testi@yahoo.com, would it be possible to get gmail.com and yahoo.com in html template by using {{DOMAIN}}.

when is the next update coming through and how can i help speed it up.
thanks awesome work once more

**Comment by GemGeorge** [comment]
Updated with this option. You can clone the repo and use {{MDOMAIN}} to get the domain from the email of the target user.

**Comment by therealelyayo** [comment]
awesome work bro you rock
