### ISSUE TITLE
who can help me ?I can log in, but the page is like the following figure. I don't know anything about PHP. What does he mean? How should I correct it

### ISSUE THREAD

**Issue by wetting** [GemGeorge/SniperPhish#11]
![批注 2021-09-27 154247](https://user-images.githubusercontent.com/90981328/134865470-2c0a07b5-13ce-431a-817f-11a9d708870a.jpg)

**Comment by evilangel1** [comment]
After I install successfully, enter the user name and password, click login, and flash back on the login page
