### ISSUE TITLE
Creating web tracker gives empty error message

### ISSUE THREAD

**Issue by pieterhouwen** [GemGeorge/SniperPhish#14]
Hi GemGeorge!

I'm trying to import the input fields of a DirectAdmin login page but it's not getting recognised. 
How can I fix this?

Relevant source code:

```
<h1>DirectAdmin Login Page</h1>
<table cellspacing=1 cellpadding=5>
<tr>
<td class=listtitle colspan=2>Please enter your Username and Password</td></tr>
<form action="/CMD_LOGIN" method="POST" name="form">
<input type=hidden name=referer value="/">
<tr><td class=list align=right>Username:</td><td class=list><input class=inset type=text name=username autocapitalize='none'></td></tr>
<tr><td class=list align=right>Password:</td><td class=list><input class=inset type=password name=password></td></tr>
<tr><td class=listtitle align=right colspan=2><input id=submit type=submit value='Login'></td></tr>
</form>
</table>
</center>
```

What would be the correct way to define the input fields for tracking?

**Comment by pieterhouwen** [comment]
The URL bar for import didn't work, but when I pasted the code I forgot to clear the URL bar, it's getting recognised now.
It's still not allowing me to create the tracker though, getting an empty error.

**Comment by GemGeorge** [comment]
The username and password fields are 'text' type. They don't have id attributes unlike submit button and that's why those fields show empty in SP.
![image](https://user-images.githubusercontent.com/15928266/136802138-a67bf461-d3b6-4cfa-961c-f431bb796f10.png)

**Comment by pieterhouwen** [comment]
Looking at the developer console I saw the response was "Access Denied". When refreshing the page I was redirected to the login page so it looks like my session was expired. Now I can save succesfully :)
