### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Chomikmarkus** [GemGeorge/SniperPhish#15]
Hello!

First hell of a good framework!! +++++
Second are you planning to add local smtp server support??
Cool would be also site cloner!

**Comment by GemGeorge** [comment]
Hi,

Thanks. Local SMTP support will be considered in the future, but a site cloner can be expected soon.

**Comment by Chomikmarkus** [comment]
But main thing buddy, contact list export

**Comment by GemGeorge** [comment]
@Chomikmarkus , are you referring to https://github.com/GemGeorge/SniperPhish/issues/18?
