### ISSUE TITLE
Option for Ignoring Certificate in SMTP settings

### ISSUE THREAD

**Issue by mdaiezatt** [GemGeorge/SniperPhish#17]
Hi,

Just wondering if there any option to ignore self-signed certificate for SMTP server in SMTP settings?

Thanks.

**Comment by GemGeorge** [comment]
Hi,

Can you please elaborate? Are you seeing any error messages related to the self-signed certificate?

**Comment by mdaiezatt** [comment]
Hi GemGeorge,

Actually i saw this error message from the application when i tried to verify Auto Mailbox Lookup.

![error_msg](https://user-images.githubusercontent.com/16186478/146048968-5146585e-de4f-4daa-9613-cfb9c5739d07.png)

Any suggestion to bypass this verification?

**Comment by GemGeorge** [comment]
I can suggest only checking the certificate you use. If you like, you can discuss in discord.
