### ISSUE TITLE
Import Recipient List

### ISSUE THREAD

**Issue by pitbullcan** [GemGeorge/SniperPhish#18]
I think there should be an option to import recipient list as it would be cumbersome of a work to enter a thousand or more emails manually.

**Comment by GemGeorge** [comment]
Hi, the import user list is already there. You can import from a CSV file containing the user's name and email addresses.
![image](https://user-images.githubusercontent.com/15928266/145581248-e65ca218-e81d-4d27-9b5c-032417973e86.png)

**Comment by Chomikmarkus** [comment]
need update framework! Thanks

**Comment by Chomikmarkus** [comment]
But there is something else! When i try to import contact list in csv it does not allow me choose file from filebrowser

**Comment by GemGeorge** [comment]
What version are you using? Have you checked from your PC?

**Comment by Chomikmarkus** [comment]
Yes on windows it let me choose file but no table content and file is not uploaded! Should file be in csv and coma separeted? First name,Last name,email?

**Comment by GemGeorge** [comment]
> Yes on windows it let me choose file but no table content and file is not uploaded! Should file be in csv and coma separeted? First name,Last name,email? No data available in table

You should be using the wrong format. You can export the user list as CSV after submitting some dummy data. Then you can use that file as csv template

**Comment by Chomikmarkus** [comment]
Still there is some issues with uploading full list to 
SniperPhish! wrote you on discord full issue! But it seems that it cannot recon some input at fails to upload!

**Comment by GemGeorge** [comment]
Ok, I'll look it in Discord

**Comment by pitbullcan** [comment]
I just updated my version and it was working. I applied this instruction from GemGeorge "You should be using the wrong format. You can export the user list as CSV after submitting some dummy data. Then you can use that file as csv template"

Thanks

**Comment by Chomikmarkus** [comment]
Yup you were right, libreoffice csv import was messing up list
