### ISSUE TITLE
PHP fatal error: Call to undefined function curl_init()

### ISSUE THREAD

**Issue by pieterhouwen** [GemGeorge/SniperPhish#19]
Hello,

When I use a tracker URL my browser returns an error 500.
Apache logs show the following:

```
[Tue Dec 07 16:47:38.549687 2021] [php7:error] [pid 50884] [client 123.123.123.123:10252] PHP Fatal error:  Uncaught Error: Call to undefined function curl_init() in /var/www/html/sniperphish/spear/common_functions.php:241\nStack trace:\n#0 /var/www/html/sniperphish/qt.php(33): getIPInfo()\n#1 {main}\n  thrown in /var/www/html/sniperphish/spear/common_functions.php on line 241
```

How can I fix this?

**Comment by GemGeorge** [comment]
Hi,

It looks like curl is not enabled in your server. You need to enable it's support. Check https://stackoverflow.com/questions/6382539/call-to-undefined-function-curl-init

**Comment by pieterhouwen** [comment]
Yes looks like that fixed it! Thanks!
