### ISSUE TITLE
Code Obfuscation

### ISSUE THREAD

**Issue by Jason-Linux** [GemGeorge/SniperPhish#20]
## Code Obfuscation

Hi !
Do you know another solution whom use code obfuscation ?

**Comment by Jason-Linux** [comment]
or where are stock the generates' javascript

**Comment by Jason-Linux** [comment]
I would like find where are store the tracker js.
To try if obfuscate js code can be use to escape google bot who blacklist my domain name

**Comment by GemGeorge** [comment]
It is stored in the database. Instead of copying the tracker link generated, you can copy the whole tracker code output and put it on the web page after obfuscating it.

**Comment by Jason-Linux** [comment]
Thanks i arrived at the same conclusion
