### ISSUE TITLE
Directory Permission Issue

### ISSUE THREAD

**Issue by ryandangalan** [GemGeorge/SniperPhish#21]
I'm having the below issue. I already set the mentioned directory to 777 but still the same. Can someone help me on this?

![image](https://user-images.githubusercontent.com/97280637/148970811-68a0cda4-117b-46f5-acc7-652926aab8c5.png)

**Comment by GemGeorge** [comment]
What command did you use? Can you write a file to that directories from a user-level account?

**Comment by ryandangalan** [comment]
This is already okay. What I did is just a clean install of a new VM.
