### ISSUE TITLE
Problem with .htaccess

### ISSUE THREAD

**Issue by gfmateo** [GemGeorge/SniperPhish#24]
Hi,

I have this problem at the instalation:

"The .htaccess file from web root is either a) missing, b)incorrectly configured or c)it's support does not enabled in your web server. SniperPhish requires web server configuration to ignore .php from URLs. You should configure .htaccess file to ignore .php extension."

I try to create the file again, but it doesn't works

I'm trying to deploy it at a Kali Linux in virtualbox, with an apache2 server.

**Comment by GemGeorge** [comment]
Did you check the suggestions a, b and c already?

**Comment by gfmateo** [comment]
Hi! yes, I check all of it. The content of my .htaccess file are the following:

Options -Indexes
RewriteEngine On
RewriteCond %{REQUEST_FILENAME} !-d
RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule ^([^\.]+)$ $1.php [NC,L]

**Comment by GemGeorge** [comment]
If you have checked all 3 suggestions, how did you manage to figure out it's a file content issue? Can you share the htacces error from the apache log?

**Comment by gfmateo** [comment]
When I tried to install the tool, I have this error:
![image](https://user-images.githubusercontent.com/26739285/170083420-6a59e449-34b4-4c1d-9d6f-f1dacc545c3d.png)

**Comment by GemGeorge** [comment]
@gfmateo , it looks like you are not sure what the error message says and how to check those for .htaccess file. If that is the case, please discuss it in our community https://www.sniperphish.com/discord.

I am closing this as this is not an SP issue.
