### ISSUE TITLE
Error .htaccess

### ISSUE THREAD

**Issue by Jason-Linux** [GemGeorge/SniperPhish#38]
I use rocky linux 8.6

I have this error message in requirement

The .htaccess file from web root is either a) missing, b)incorrectly configured or c)it's support does not enabled in your web server. SniperPhish requires web server configuration to ignore .php from URLs. You should configure .htaccess file to ignore .php extension.

I config all but still remains

**Comment by GemGeorge** [comment]
Check https://unixcop.com/how-to-enable-mod_rewrite-for-apache-in-rocky-linux-8-alma-linux-8/

You can write a simple .php file and check if you can access it without appending .php in the URL.

**Comment by Jason-Linux** [comment]
with and without don't work, now i'm using debian based distrib and its working
