### ISSUE TITLE
PHP 8.1 INSTALL

### ISSUE THREAD

**Issue by mateocrx** [GemGeorge/SniperPhish#39]
Hello,

I want to install sniperphish, but it tells me that my PHP version is 8.0.27 while on the info page of php I am well in 8.1.15.

I have already re-uploaded the files but it doesn't help.

How can I do ?

![Capture1](https://user-images.githubusercontent.com/113882813/221607722-b146e8d0-f3ec-4412-ac71-73be4747431b.PNG)
![Capture](https://user-images.githubusercontent.com/113882813/221607733-71251337-a9f7-473e-aacf-621e8ed91573.PNG)

**Comment by GemGeorge** [comment]
Thanks for pointing that out. Fixed here https://github.com/GemGeorge/SniperPhish/commit/2361111759cfa9dd46a4a6f8ac3b5adec9a8b004

**Comment by mateocrx** [comment]
Hi! 

It still doesn't work for me. The solution I found is to delete the following line in the htaccess.
![image](https://user-images.githubusercontent.com/113882813/221797652-f7a3b956-307d-48f2-85b8-9c3458a52f92.png)

**Comment by GemGeorge** [comment]
Great. That part is no longer required, as it is generated by the hosting. I'll remove it from the repo also.

**Comment by mateocrx** [comment]
Perfect! Thank you for your responsiveness!
