### ISSUE TITLE
Stored XSS via form data submitted by the phishing victim

### ISSUE THREAD

**Issue by dunderhay** [GemGeorge/SniperPhish#4]
A phishing victim can send an XSS payload that triggers in the SniperPhish admin panel. 

As an example, this basic phishing landing page has a single form which accepts a username field from the phishing victim.

![Screen Shot 2021-05-08 at 9 00 40 pm](https://user-images.githubusercontent.com/27876907/117536793-81fa6b80-b040-11eb-85a5-e69998c5c8d8.png)

The XSS is triggered when the admin views the Campaign Results in the `WebMailCmpDashboard` page.

![Screen Shot 2021-05-08 at 9 03 53 pm](https://user-images.githubusercontent.com/27876907/117537026-d05c3a00-b041-11eb-8c0c-f57aae0d11e4.png)

![Screen Shot 2021-05-08 at 9 06 24 pm](https://user-images.githubusercontent.com/27876907/117536984-870bea80-b041-11eb-9fb8-bf8c44a02a56.png)
 
Unlike the previous XSS I reported, this stored XSS can be triggered by the external phishing victim (via submitted form field data) and can be used to target admin users.

**Comment by dunderhay** [comment]
I tested this as a temporary fix, but you probably want to create a function to escape html yourself (perhaps in the common js scripts directory) and use it everywhere you interpolate user data. 

```diff
diff --git a/spear/js/web_mail_campaign_dashboard.js b/spear/js/web_mail_campaign_dashboard.js
index 7db95e9..186830a 100644
--- a/spear/js/web_mail_campaign_dashboard.js
+++ b/spear/js/web_mail_campaign_dashboard.js
@@ -1453,6 +1453,13 @@ function auxData_wfs(column,m_item){
         return "<td>-</td>";
 }

+function escapeHtml(text) {
+    'use strict';
+    return text.replace(/[\"&<>]/g, function (a) {
+        return { '"': '&quot;', '&': '&amp;', '<': '&lt;', '>': '&gt;' }[a];
+    });
+}
+
 function auxData_form_fields(column,m_item){
     var hit_items = [];
     var tb_data='';
@@ -1473,10 +1480,10 @@ function auxData_form_fields(column,m_item){
         if(hit_items[0] == false)
             tb_data = "<td><center><i class='fas fa-times fa-lg text-danger' data-toggle='tooltip' title='No'></i><span hidden>No</span></center></td>";
         else
-            tb_data += "<td>" + hit_items[0] + "</td>";
+            tb_data += "<td>" + escapeHtml(hit_items[0]) + "</td>";
     }
     else
-        tb_data += hit_items.length>0 ? "<td>"+hit_items.join(",\r\n")+"</td>":"<td>-</td>";
+        tb_data += hit_items.length>0 ? "<td>" + escapeHtml(hit_items.join(",\r\n")) + "</td>":"<td>-</td>";

     return tb_data;
 }
@@ -1956,4 +1963,4 @@ function hideMeFromPublic(){
     $(".topbar").hide();
     $(".page-wrapper").css('margin-left',0);
     $(".item_private").hide();
-}
\ No newline at end of file
+}
```

![Screen Shot 2021-05-08 at 10 04 06 pm](https://user-images.githubusercontent.com/27876907/117538403-592aa400-b049-11eb-9967-c3ab5e6b80c9.png)

**Comment by sreesec** [comment]
Hey man, thanks for the awesome finding. I'll look into it. Meanwhile feel free to submit if you find more issues.
Cheers,
Sree.

**Comment by GemGeorge** [comment]
A permanent fix is implemented at PHP file using `htmlspecialchars ()` here https://github.com/GemGeorge/SniperPhish/commit/61cb73a4e5e156638c761334a5f9f36aaf20ecdc and https://github.com/GemGeorge/SniperPhish/commit/6ace1c3bba5b106acb8a93b0a44c2f737d33c3a1
