### ISSUE TITLE
Import User Problem

### ISSUE THREAD

**Issue by Jason-Linux** [GemGeorge/SniperPhish#42]
Hello, 

I can't import User for my mail campaign.
I use the good format.
But i get error like : 

```log
DataTables warning: table id=table_user_list - Ajax error. For more information about this error, please see http://datatables.net/tn/7
```

Server's logs

```log
PHP Fatal error:  Uncaught Error: Call to undefined function isValidEmail()
```

**Comment by GemGeorge** [comment]
Thanks, fixed here https://github.com/GemGeorge/SniperPhish/commit/8795e22e37171ac67271f84d2c9cb59f2ef1f0ee
