### ISSUE TITLE
Problem 'Command - awk' | Install

### ISSUE THREAD

**Issue by mateocrx** [GemGeorge/SniperPhish#43]
Hi,

I changed my host and I'm now on OVH.
But during the installation it tells me that 'command - awk' is not present.

I have an ovh web hosting.
I can't install the command manually because I don't have access to SSH with my current offer

 How to do it ?
![image](https://user-images.githubusercontent.com/113882813/232539958-46de310d-9176-456a-ac7e-7767d60a80c5.png)

**Comment by GemGeorge** [comment]
It looks like you need to contact hosting provider

**Comment by mateocrx** [comment]
OVH told me that they can't install additional packages so I can't install the 'gawk' package. 
I'll have to get a vps
