### ISSUE TITLE
IMPORT CSV EMAIL

### ISSUE THREAD

**Issue by mateocrx** [GemGeorge/SniperPhish#44]
I can't import a csv. However I changed line 460 to "function isValidEmail($email) { //supports RFC 5322".

I now have this error:
![image](https://user-images.githubusercontent.com/113882813/233773024-dbec383c-848e-4829-8497-dfd132c69d2b.png)

**Comment by GemGeorge** [comment]
Can you share a sample mail causing the error?

**Comment by mateocrx** [comment]
I put a test email in this file.
Otherwise I have 57 people.
[test.csv](https://github.com/GemGeorge/SniperPhish/files/11301201/test.csv)

**Comment by GemGeorge** [comment]
The CSV file is in wrong format. Add contents in correct structure. Check https://docs.sniperphish.com/getting-started/email-campaign/user-group

**Comment by mateocrx** [comment]
I added "First Name", "Last Name" and others... but I still have the error
[test.csv](https://github.com/GemGeorge/SniperPhish/files/11301767/test.csv)

**Comment by GemGeorge** [comment]
Why are you using semi-colon as a separator in CSV? What application are you using to create CSV file?

**Comment by GemGeorge** [comment]
You should use comma instead of semi-colon for separating values.

**Comment by mateocrx** [comment]
I use excel, and yet I exported in .csv

**Comment by mateocrx** [comment]
I tried with several software, it does not solve anything

**Comment by mateocrx** [comment]
I solved the problem, but I don't know how.
Weird
Thanks for your reactivity GEM!
