### ISSUE TITLE
Attachment tracking

### ISSUE THREAD

**Issue by AkatsukiSec** [GemGeorge/SniperPhish#5]
Hey,

this is not an issue but more like feature request. Is there a way or on the roadmap somehow (canarytokens?) to track attachment opens?

Thanks

**Comment by GemGeorge** [comment]
The canary token actually works by making a call back to the hosting server. In my understanding, an attachment is sent along with the mail body and which downloads from the receiver's mail server. In the download, the only communication happening is between the receiver's mail server and the computer of the user who downloads. Hence there is no callback can be made to the hosting server of SniperPhish. 

However, there are certain ways we can track attachments, but not a straightforward way:
1. By hosting a web page - where you send a mail with a link to the web page. The user clicks the link and the page opens in his web browser. The user can download the attachment file from the web page (manually or an auto-download). This one you can do with the help of SniperHost module in the SniperPhish
2. Embedding a payload in the attachment - once the user opens the attachment, a callback can be retrieved. If you can craft that for generating a web request, the Quick tracker module can help to track. Web Tacker can also be used in some tricky way - by generating code for a dummy page and using its callback URL directly in the payload.

From the above, the 1st one tracks attachment downloads and 2nd one tracks attachment open. Would be nice if you can find a better option to track attachment downloads.

**Comment by AkatsukiSec** [comment]
I understand your points. But in these cases how would you know which user opened an attachment if you have single payload for everyone? The payload and the attachment would have to be generated by SniperPhish when starting a campaign.

**Comment by AkatsukiSec** [comment]
Yes it would be a huge advantage against for lets say gophish where useres are calling for this feature like 3 years. Office formats like docx are mainly just a bunch of xml files. You could as a user make a template file and insert a macro. Then before sending SniperPhish could just append a callback to this macro with unique link for each user.

**Comment by GemGeorge** [comment]
Yes, we can add an option to send unique attachments. Closing this thread now. More ideas are welcome to discuss in our Discord channel

**Comment by GemGeorge** [comment]
@AkatsukiSec , added feature to rename attachment on-the-fly. Hope the requested feature is partially implemented. Updated release is at https://github.com/GemGeorge/SniperPhish/releases/tag/v1.2
