### ISSUE TITLE
installation does not work

### ISSUE THREAD

**Issue by rrcyber** [GemGeorge/SniperPhish#6]
I put the url in my server as indicated in the readme.md file http://localhost/SniperPhish/install and I get this error message:

Not Found
The requested URL was not found on this server.

**Comment by rrcyber** [comment]
And when I put the url in my serverhttp://localhost/SniperPhish/install.php I get this error message:

Requirements check
Can not access /install_manager without using .php extension in the URL. SniperPhish requires web server configuration to ignore .php from URLs. A common reason for the error is that your web server is not detecting the .htaccess file. Check .htaccess file in the SniperPhish root directory and enable .htaccess support in your web server.

**Comment by GemGeorge** [comment]
Hi, can you please clarify your query? I see both the issue its resolution in your message.

**Comment by leezp** [comment]
how to deal with it please

**Comment by GemGeorge** [comment]
> how to deal with it please

Please clarify your issue

**Comment by leezp** [comment]
my problem is same as @rrcyber

**Comment by GemGeorge** [comment]
@leezp the solution also posted by @rrcyber. Please check his 2nd message. This is the same that the installer suggests fixing the issue.

>SniperPhish requires web server configuration to ignore .php from URLs. A common reason for the error is that your web server is not detecting the .htaccess file. Check .htaccess file in the SniperPhish root directory and enable .htaccess support in your web server.

**Comment by GemGeorge** [comment]
@leezp , if your facing any installation issue, please discuss it in the discord channel https://sniperphish.com/discord
