### ISSUE TITLE
Feature request: Infected attachments (doc, xlsx etc)

### ISSUE THREAD

**Issue by pieterhouwen** [GemGeorge/SniperPhish#7]
In the readme I only saw "Auto renaming attachments on the fly" but not other mentions of attachments.
Would be interesting to know how much of your users will enable macro's for example.

Macro could show scareware or an educational message for the end-user.

**Comment by GemGeorge** [comment]
You can use {{CID}} to name attachments on-the-fly to uniquely identify them. If you use doc or excel file attachment, the macro can be used to read own file name. Check https://stackoverflow.com/questions/1895616/how-to-get-the-excel-file-name-path-in-vba/1896057
Then you can use macro to send web request to the Quick tracker link. Eg: https://<SP>/qt?tid=xxx&cid=<attachment name>
Then the Quick tracker tracks attachment open.
