### ISSUE TITLE
Email template encoding problem

### ISSUE THREAD

**Issue by zhimiyouwu33** [GemGeorge/SniperPhish#8]
The email template title does not support other languages, such as Chinese email, it will report an error and cannot be saved.

**Comment by GemGeorge** [comment]
Do you mean mail subject? I see no issues on saving in any language. Do you have a screenshot?

**Comment by zhimiyouwu33** [comment]
![image](https://user-images.githubusercontent.com/75343826/126271498-75179a90-428e-4be5-bdd6-2e6c82230a16.png)
Can't save。

![image](https://user-images.githubusercontent.com/75343826/126271778-59530587-d67d-48ca-ab3f-c538697a406d.png)
It's normal to change to English。

**Comment by zhimiyouwu33** [comment]
> Do you mean mail subject? I see no issues on saving in any language. Do you have a screenshot?

![image](https://user-images.githubusercontent.com/75343826/126271498-75179a90-428e-4be5-bdd6-2e6c82230a16.png)
Can't save。

![image](https://user-images.githubusercontent.com/75343826/126271778-59530587-d67d-48ca-ab3f-c538697a406d.png)
It's normal to change to English。

**Comment by zhimiyouwu33** [comment]
> Do you mean mail subject? I see no issues on saving in any language. Do you have a screenshot?

![image](https://user-images.githubusercontent.com/75343826/126273236-32c5d429-6d68-4531-b81c-8440a99d4b6e.png)
![image](https://user-images.githubusercontent.com/75343826/126273487-a8b27d64-e121-45dd-8198-fdd5cb9a70b7.png)

I copied a Linked html email template, but it can't be saved smoothly.

**Comment by GemGeorge** [comment]
I tried with multiple languages. Still can't find any issues. Appreciate it if you can connect through the discord channel to discuss further https://sniperphish.com/discord
![image](https://user-images.githubusercontent.com/15928266/126285006-6cfe8255-0fb0-47b2-960d-8647e980fbfd.png)

**Comment by zhimiyouwu33** [comment]
> I tried with multiple languages. Still can't find any issues. Appreciate it if you can connect through the discord channel to discuss further https://sniperphish.com/discord
> ![image](https://user-images.githubusercontent.com/15928266/126285006-6cfe8255-0fb0-47b2-960d-8647e980fbfd.png)

When using MariaDB10.3 on Debian10, this problem occurs with UTF8 and utf8mb4. Which database do you have not reported an error?
